var nifty50 = [
  {"symbol": "ADANIENT", "name": "Adani Enterprises"},
  {"symbol": "ADANIPORTS", "name": "Adani Ports and SEZ"},
  {"symbol": "APOLLOHOSP", "name": "Apollo Hospitals"},
  {"symbol": "ASIANPAINT", "name": "Asian Paints"},
  {"symbol": "AXISBANK", "name": "Axis Bank"},
  {"symbol": "BAJAJ-AUTO", "name": "Bajaj Auto"},
  {"symbol": "BAJFINANCE", "name": "Bajaj Finance"},
  {"symbol": "BAJAJFINSV", "name": "Bajaj Finserv"},
  {"symbol": "BHARTIARTL", "name": "Bharti Airtel"},
  {"symbol": "BPCL", "name": "Bharat Petroleum"},
  {"symbol": "BRITANNIA", "name": "Britannia Industries"},
  {"symbol": "CIPLA", "name": "Cipla"},
  {"symbol": "COALINDIA", "name": "Coal India"},
  {"symbol": "DIVISLAB", "name": "Divi's Laboratories"},
  {"symbol": "DRREDDY", "name": "Dr. Reddy's Laboratories"},
  {"symbol": "EICHERMOT", "name": "Eicher Motors"},
  {"symbol": "GRASIM", "name": "Grasim Industries"},
  {"symbol": "HCLTECH", "name": "HCL Technologies"},
  {"symbol": "HDFCBANK", "name": "HDFC Bank"},
  {"symbol": "HDFCLIFE", "name": "HDFC Life Insurance"},
  {"symbol": "HEROMOTOCO", "name": "Hero MotoCorp"},
  {"symbol": "HINDALCO", "name": "Hindalco Industries"},
  {"symbol": "HINDUNILVR", "name": "Hindustan Unilever"},
  {"symbol": "ICICIBANK", "name": "ICICI Bank"},
  {"symbol": "ITC", "name": "ITC Ltd"},
  {"symbol": "INDUSINDBK", "name": "IndusInd Bank"},
  {"symbol": "INFY", "name": "Infosys"},
  {"symbol": "JSWSTEEL", "name": "JSW Steel"},
  {"symbol": "KOTAKBANK", "name": "Kotak Mahindra Bank"},
  {"symbol": "LT", "name": "Larsen & Toubro"},
  {"symbol": "M&M", "name": "Mahindra & Mahindra"},
  {"symbol": "MARUTI", "name": "Maruti Suzuki"},
  {"symbol": "NTPC", "name": "NTPC Ltd"},
  {"symbol": "NESTLEIND", "name": "Nestle India"},
  {"symbol": "ONGC", "name": "Oil & Natural Gas Corporation"},
  {"symbol": "POWERGRID", "name": "Power Grid Corporation"},
  {"symbol": "RELIANCE", "name": "Reliance Industries"},
  {"symbol": "SBILIFE", "name": "SBI Life Insurance"},
  {"symbol": "SBIN", "name": "State Bank of India"},
  {"symbol": "SUNPHARMA", "name": "Sun Pharmaceutical"},
  {"symbol": "TCS", "name": "Tata Consultancy Services"},
  {"symbol": "TATACONSUM", "name": "Tata Consumer Products"},
  {"symbol": "TATAMOTORS", "name": "Tata Motors"},
  {"symbol": "TATASTEEL", "name": "Tata Steel"},
  {"symbol": "TECHM", "name": "Tech Mahindra"},
  {"symbol": "TITAN", "name": "Titan Company"},
  {"symbol": "ULTRACEMCO", "name": "UltraTech Cement"},
  {"symbol": "UPL", "name": "UPL Ltd"},
  {"symbol": "WIPRO", "name": "Wipro"}
];